gui:
  theme:
    activeBorderColor:
      - "#a6da95"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitFgColor:
      - "#8aadf4"
    cherryPickedCommitBgColor:
      - "#494d64"
    markedBaseCommitFgColor:
      - "#8aadf4"
    markedBaseCommitBgColor:
      - "#494d64"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"
